import { ToastContainer } from "react-toastify";
import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./app.css";
import "../app/dashboard.scss";
import "../app/scrollbar.scss";
import "../app/modal.scss";
import { ThemeProvider } from "next-themes";
import SyncfusionLicenseProvider from "@/components/syncfusion-license-provider/page";
import ReduxProvider from "../providers/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ledger-X Admin",
  description: "Generated by create next app",
  icons: {
    icon: "/icon/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <ReduxProvider>
            <SyncfusionLicenseProvider>{children}</SyncfusionLicenseProvider>
          </ReduxProvider>
        </ThemeProvider>
        <ToastContainer position="bottom-right" limit={1} />
      </body>
    </html>
  );
}
