import type { Metadata } from "next";
import OrganizationBar from "@/@/component/organization-bar";
import DashboardStructure from "@/@/component/dashboard-structure";

export const metadata: Metadata = {
  title: "Ledger-X Admin",
  description: "Generated by create next app",
  icons: {
    icon: "/icon/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="layout">
      <div className="dashboard_main_div">
        <div className="main_div_left_side">
          <div className="organization_bar_main_div">
            <OrganizationBar />
          </div>
        </div>
        <div className="main_div_right_side">
          <DashboardStructure>{children}</DashboardStructure>
        </div>
      </div>
      {/* <ToastContainer /> */}
    </div>
  );
}
